const moo = require('moo');

let lexer = moo.compile({
  ws: /[ \t]+/,
  comment: /\/\/.*?$/,
  mlstart: /\/\*/,
  mlend: /\*\//,
  number: /0|[1-9][0-9]*/,
  string: [/"(?:\\["\\]|[^\n"\\])*"/, /'(?:\\["\\]|[^\n"\\])*'/],
  lparen: '(',
  rparen: ')',
  lbrace: '{',
  rbrace: '}',
  lsquarebracket: '[',
  rsquarebracket: ']',
  keyword: ['while', 'if', 'else', 'moo', 'cows'],
  fatarrow: '=>',
  identifier: /[a-zA-z][a-zA-Z0-9]*/,
  minus: '-',
  plus: '+',
  times: '*',
  divide: '/',
  mod: '%',
  caret: '^',
  pound: '#',
  dollar: '$',
  at: '@',
  amper: '&',
  tilda: '~',
  backtick: '`',
  lessthan: '<',
  greaterthan: '>',
  equalto: /===|==/,
  notequalto: /!==|!=/,
  excl: '!',
  colon: ':',
  assign: '=',
  comma: ',',
  keywords: ['if', 'each'],
  nl: { match: /\r\n/, lineBreaks: true },
});

module.exports = lexer;
